### PR TITLE
[BE] Login - Logout - Register

### PR DESCRIPTION
**Pull request by DTHNhung**
## Related Tickets:

-   [#45930](https://edu-redmine.sun-asterisk.vn/projects/ecommerce-intern-hn/issues)

## WHAT this PR does?

- back-end login - logout - register

## Notes Impacted Areas:

-   N/A.

## Attachments:

-   N/A.

### CODE REVIEW

**Comment by khieutrung12** [comment]
ok

**Comment by DTHNhung** [comment]
ready

**Comment by DTHNhung** [comment]
ready

**Review by huyenttm-0901 — COMMENTED** [review]
em ơi, gộp commit nhé

**Comment by DTHNhung** [comment]
ready

**Comment by ghost** [comment]
merged

**Pull request merged**
